Update to WRF38

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6,18 +6,21 @@ thiscmd=$0
 
 FORTRAN_COMPILER_TIMER=""
 opt_level="-f"
+rword="-r4"
 print_usage=""
 chemistry=""
 wrf_core=""
 while [ $# -ge 1 ]; do
     case $1 in
       -d) opt_level="-d" ;;
+      -D) opt_level="-D" ;;
       -s) opt_level="-s" ;;
       -f) opt_level="-f" ;;
       -h) print_usage="yes" ;;
       -help) print_usage="yes" ;;
       -os) shift ; WRF_OS=$1 ;;
       -mach) shift ; WRF_MACH=$1 ;;
+      -r8) rword="-r8" ;;
       -time) shift ; FORTRAN_COMPILER_TIMER=$1 ;;
       chem) WRF_CHEM=1  ;;
       kpp) WRF_KPP=1  ;;
@@ -35,7 +38,15 @@ while [ $# -ge 1 ]; do
     shift
 done
 if [ -n "$print_usage" ] ; then
-  echo usage: $thiscmd '[-d|-s|-f|-os os|-mach mach|-time timecommand] [chem] [kpp]'
+  echo ' '
+  echo '*****************************************************************************'
+  echo usage: $thiscmd '[-d|-D|-s|-f|-os os|-mach mach|-time timecommand] [chem] [kpp]'
+  echo '-d    build with debugging information and no optimization'
+  echo '-D    build with -d AND floating traps, traceback, uninitialized variables'
+  echo '-r8   build with 8 byte reals'
+  echo '-help print this message'
+  echo '*****************************************************************************'
+  echo ' '
   exit 
 fi
 
@@ -276,13 +287,99 @@ fi
 USENETCDFF=""  # see below
 if [ -n "$NETCDF" ] ; then
   echo "Will use NETCDF in dir: $NETCDF"
-# for 3.6.2 and greater there might be a second library, libnetcdff.a .  Check for this and use 
-# if available
-  if [ -f "$NETCDF/lib/libnetcdff.a" ] ; then
+# Oh UNIDATA, why make it so hard ...
+  if [ -f "$NETCDF/lib/libnetcdff.a" -o -f "$NETCDF/lib/libnetcdff.so" ] ; then
     USENETCDFF="-lnetcdff"
+  else
+    USENETCDFF=" "
+  fi
+  if [ -f "$NETCDF/lib/libnetcdf.a" -o -f "$NETCDF/lib/libnetcdf.so" ] ; then
+    USENETCDF="-lnetcdf"
+  else
+    USENETCDF=" "
   fi
 else
   echo "Will configure for use without NetCDF"
+fi
+
+if [ -z "$HDF5_PATH" ] ; then HDF5_PATH=''; fi
+if [ -z "$ZLIB_PATH" ] ; then ZLIB_PATH=''; fi
+if [ -z "$GPFS_PATH" ] ; then GPFS_PATH=''; fi
+if [ -z "$CURL_PATH" ] ; then CURL_PATH=''; fi
+
+if [ -n "$NETCDF4" ] ; then
+  if [ $NETCDF4 -eq 1 ] ; then
+    DEP_LIB_PATH=''
+    if [ -f $NETCDF/bin/nf-config ] ; then
+      nx_config="$NETCDF/bin/nf-config --flibs"
+      DEP_LIB_PATH="`$nx_config | awk '{for(i=1;i<=NF;i++){if(match($i, /-L.*/)) {print $i} } }'`"
+      CURL="`$nx_config | awk '{for(i=1;i<=NF;i++){if($i == "-lcurl") {print $i} } }'`"
+      GPFS="`$nx_config | awk '{for(i=1;i<=NF;i++){if($i == "-lgpfs") {print $i} } }'`"
+    fi
+    if [ "$DEP_LIB_PATH" = '' ] ; then
+      if [ -f $NETCDF/bin/nc-config ] ; then
+        nx_config="$NETCDF/bin/nc-config --libs"
+        DEP_LIB_PATH="`$nx_config | awk '{for(i=1;i<=NF;i++){if(match($i, /-L.*/)) {print $i} } }'`"
+        CURL="`$nx_config | awk '{for(i=1;i<=NF;i++){if($i == "-lcurl") {print $i} } }'`"
+        GPFS="`$nx_config | awk '{for(i=1;i<=NF;i++){if($i == "-lgpfs") {print $i} } }'`"
+        if [ "$CURL" != '' -a  "$CURL_PATH" = '' ] ; then
+           CURL_PATH="DEFAULT"
+        fi
+        if [ "$GPFS" != '' -a  "$GPFS_PATH" = '' ] ; then
+           GPFS_PATH="DEFAULT"
+        fi
+      fi
+    fi
+    for P in "$HDF5_PATH" "$ZLIB_PATH" "$GPFS_PATH" "$CURL_PATH"
+    do
+      if [ "$P" != '' -a "$P" != "DEFAULT" ] ; then 
+        if [ "${P#${P%?}}" = "/" ] ; then
+          P=`echo $P | sed 's/\/$//'`
+        fi
+        DEP_LIB_PATH="`echo $DEP_LIB_PATH | awk -v VAR=-L$P/lib '{for(i=1;i<=NF;i++){if ($i != VAR ) {print $i} } }'`"
+        DEP_LIB_PATH="$DEP_LIB_PATH -L$P/lib"
+      fi
+    done
+    if [ "${NETCDF#${NETCDF%?}}" = "/" ] ; then
+      NETCDF=`echo $NETCDF | sed 's/\/$//'`
+    fi
+    buff="`ls -l $NETCDF | sed 's/  */ /g'`"
+    while [ "`echo $buff | grep lib`" = "" -a "`echo $buff | grep '\->'`" != ""  ]
+    do
+      buff="`echo $buff | sed -e 's/->//' -e 's/  */ /g'`"
+      n=`echo $buff | wc -w`
+      lastword=`echo "$buff" | cut -d' ' -f$n | sed 's/\/$//'`
+      c="`echo $lastword | cut -c1`"
+      if [ "$c" == "/" ] ; then
+         NETCDF=$lastword
+      else
+        c="`echo $lastword | cut -c1-2`"
+        if [ "$c" = "./" ] ; then
+          lastword="echo $lastword | cut -c3-"
+        fi
+        NETCDF=${NETCDF%/*}/$lastword
+      fi
+      buff="`ls -l $NETCDF | sed 's/  */ /g'`"
+    done 
+    if [ "`echo $NETCDF | grep '..'`"  != "" ] ; then
+      buff="`echo $NETCDF | sed -e 's/^\///' -e 's/\// /g'`"
+      n=`echo $buff | wc -w`
+      i=1
+      while [ $i -le $n ]
+      do
+        if [ "`echo $buff | cut -d' ' -f$i`" = ".." ] ; then
+          m=$i 
+        fi
+        i=$(( $i + 1 ))
+      done
+      m=$(( $m + 1 ))
+      NETCDF=/"`echo $buff | cut -d' ' -f${m}- | sed 's/  */\//g'`"
+    fi
+    if [ "${DEP_LIB_PATH#${DEP_LIB_PATH%?}}" = "/" ] ; then
+      DEP_LIB_PATH=`echo $DEP_LIB_PATH | sed 's/\/$//'`
+    fi
+    DEP_LIB_PATH="`echo $DEP_LIB_PATH | awk -v VAR=-L$NETCDF/lib '{for(i=1;i<=NF;i++){if ($i != VAR ) {print $i} } }'`"
+  fi
 fi
 
 if [ -n "$PNETCDF" ] ; then
@@ -292,16 +389,16 @@ if [ -n "$PNETCDF" ] ; then
 #  echo "Will configure for use without NetCDF"
 fi
 
+if [ -n "$HDF5" ] ; then
+  echo "Will use HDF5 in dir: $HDF5"
+else
+  echo "HDF5 not set in environment. Will configure WRF for use without."
+fi
+
 if [ -n "$PHDF5" ] ; then
   echo "Will use PHDF5 in dir: $PHDF5"
 else
   echo "PHDF5 not set in environment. Will configure WRF for use without."
-fi
-
-if [ "$wrf_core" = "DA_CORE" ]; then
-   if [ -n "$WRFPLUS_DIR" ] ; then
-      unset WRFPLUS_DIR
-   fi
 fi
 
 if [ "$wrf_core" = "4D_DA_CORE" ]; then
@@ -310,6 +407,11 @@ if [ "$wrf_core" = "4D_DA_CORE" ]; then
    else
       echo "WRFPLUS_DIR not set in environment. Please compile WRFPLUS and set WRFPLUS_DIR."
       exit
+   fi
+else
+   if [ -n "$WRFPLUS_DIR" ] ; then
+      echo 'Unsetting "$WRFPLUS_DIR" environment variable. Use "configure 4dvar" to configure for 4dvar compilation.'
+      unset WRFPLUS_DIR
    fi
 fi
 # Users who are cross-compiling can set environment variable 
@@ -368,6 +470,16 @@ fi
 
 # compile options that come from the environment, such as chemistry
 # the "!" is removed by Config_new.pl
+if [ -n "$WRF_HYDRO" ] ; then
+  if [ $WRF_HYDRO = 1 ] ; then
+      echo building WRF-HYDRO 
+      compileflags="${compileflags}!-DWRF_HYDRO"
+      echo $compileflags
+  fi
+fi
+
+# compile options that come from the environment, such as chemistry
+# the "!" is removed by Config_new.pl
 if [ -n "$WRF_MARS" ] ; then
   if [ $WRF_MARS = 1 ] ; then
     echo building WRF for Mars
@@ -378,19 +490,35 @@ fi
 
 if [ -n "$WRF_TITAN" ] ; then
   if [ $WRF_TITAN = 1 ] ; then
-    echo building WRF for Mars
+    echo building WRF for Titan
     compileflags="${compileflags}!-DPLANET!-DTITAN"
   fi
 fi
 
 if [ -n "$WRF_VENUS" ] ; then
   if [ $WRF_VENUS = 1 ] ; then
-    echo building WRF for Mars
+    echo building WRF for Venus
     compileflags="${compileflags}!-DPLANET!-DVENUS"
   fi
 fi
+if [ -n "$WRF_QUIETLY" ]; then
+  echo WRF_QUIETLY is now a synonym for WRF_LOG_BUFFERING
+  echo setting WRF_LOG_BUFFERING to 1...
+  export WRF_LOG_BUFFERING=1
+fi
+if [ -n "$WRF_LOG_BUFFERING" ]; then
+  if [ $WRF_LOG_BUFFERING = 1 ]; then
+    echo building WRF with support for buffering of log messages
+    compileflags="${compileflags}!-DWRF_LOG_BUFFERING=1"
+  fi
+fi
+if [ -n "$PNETCDF_QUILT" ]; then
+  echo Enabling quilt_pnc I/O server implementation.
+  compileflags="${compileflags}!-DPNETCDF_QUILT=1"
+fi
 if [ -n "$WRF_NMM_CORE" ]; then
   if [ $WRF_NMM_CORE = 1 ]; then
+    export WRF_NMM_NEST=1
     if [ -n "$HWRF" ]; then
       if [ $HWRF = 1 ]; then
         echo building WRF with HWRF option
@@ -432,8 +560,34 @@ else
   compileflags="${compileflags} "
 fi
 
-if [ `which timex` ] ; then
+if [ -n "$WRF_NMM_CORE" -a -n "$WRF_CHEM" ]; then
+  if [ $WRF_NMM_CORE = 1  -a  $WRF_CHEM = 1 ]; then
+    echo
+    echo "NMM is no longer compatible with the Chemistry option."
+    echo
+    # alphabetically: c=3, o=15, so co2 = 3+15+2 = 20
+    exit 20
+  fi
+fi
+
+type m4 > /dev/null
+if [ $? -ne 0 ] ; then
+  echo
+  echo "ERROR ERROR ERROR ERROR ERROR ERROR ERROR"
+  echo "'m4' utility not found! Can not configure."
+  echo
+  echo "If on an Ubuntu machine, use the command"
+  echo "         sudo apt-get install m4        "
+  echo "To download and install the 'm4' utility"
+  exit 1
+fi
+
+if command -v timex > /dev/null 2>&1; then
   FORTRAN_COMPILER_TIMER=timex
+  echo "Will use 'timex' to report timing information"
+elif command -v time > /dev/null 2>&1; then
+  FORTRAN_COMPILER_TIMER=time
+  echo "Will use 'time' to report timing information"
 fi
 
 # Found perl, so proceed with configuration
@@ -441,15 +595,32 @@ if test -n "$PERL" ; then
    srch=`grep -i "^#ARCH.*$os" arch/configure_new.defaults | grep -i "$mach"`
    if [ -n "$srch" ] ; then
      $PERL arch/Config_new.pl -dmparallel=$COMMLIB -ompparallel=$OMP -perl=$PERL \
-          -netcdf=$NETCDF -pnetcdf=$PNETCDF -phdf5=$PHDF5 -os=$os -mach=$mach -ldflags=$ldflags \
-          -compileflags=$compileflags -opt_level=$opt_level -USENETCDFF=$USENETCDFF -time=$FORTRAN_COMPILER_TIMER \
-          -wrf_core=$wrf_core
+          -netcdf=$NETCDF -pnetcdf=$PNETCDF -hdf5=$HDF5 -phdf5=$PHDF5 -os=$os -mach=$mach -ldflags=$ldflags \
+          -compileflags=$compileflags -opt_level=$opt_level -USENETCDFF=$USENETCDFF -USENETCDF=$USENETCDF \
+          -time=$FORTRAN_COMPILER_TIMER \
+          -wrf_core=$wrf_core -gpfs=$GPFS_PATH -curl=$CURL_PATH -dep_lib_path="$DEP_LIB_PATH"
      if test ! -f configure.wrf ; then
+       echo "configure.wrf not created! Exiting configure script..."
        exit 1
      fi
      if [ "$opt_level" = "-d" ] ; then
+        sed -e 's/FCOPTIM[	 ]*=/& # /' -e '/FCDEBUG[	 ]*=/s/#//' configure.wrf > configure.wrf.edit
+        /bin/mv configure.wrf.edit configure.wrf
+     fi
+     if [ "$opt_level" = "-D" ] ; then
         sed -e 's/FCOPTIM[	 ]*=/& # /' -e '/FCDEBUG[	 ]*=/s/#//g' configure.wrf > configure.wrf.edit
         /bin/mv configure.wrf.edit configure.wrf
+     fi
+
+     # GNU has a funny way of doing promotion to real*8
+     if [ "$rword" = "-r8" ] ; then
+       srch=`grep -i "^SFC" configure.wrf | grep -i "gfortran"`
+       if [ -n "$srch" ] ; then
+         sed -e '/^PROMOTION/s/#//' configure.wrf > configure.wrf.edit
+       else
+         sed -e '/^RWORDSIZE/s/$(NATIVE_RWORDSIZE)/8/' configure.wrf > configure.wrf.edit
+       fi
+       /bin/mv configure.wrf.edit configure.wrf
      fi
    else
      WRF_OS=$os ; export WRF_OS
@@ -537,6 +708,17 @@ echo "If you wish to change the default options, edit the file:"
 echo "     arch/configure_new.defaults"
 
 if test -n "$NETCDF" ; then
+  if [ ! -f $NETCDF/include/netcdf.inc ] ; then
+    echo
+    echo "Error : Not found $NETCDF/include/netcdf.inc"
+    echo "        Please check this installation of NetCDF and re-run this configure script"
+    echo
+    if test -n "$NETCDF4" ; then
+        echo "If on the NCAR Supercomputers, cp 'configure.nc4' to 'configure' and re-run script"
+        echo
+    fi
+    exit -1
+  fi
   grep nf_format_64bit $NETCDF/include/netcdf.inc > /dev/null
   configure_aaaa=$? ; export configure_aaaa
   if [ $configure_aaaa -a -z "$WRFIO_NCD_LARGE_FILE_SUPPORT" ] ; then
@@ -549,8 +731,8 @@ fi
 echo "  "
 
 if [ "$wrf_core" = "DA_CORE" -o "$wrf_core" = "4D_DA_CORE" ]; then
-  if [ "`grep '^SFC' configure.wrf | grep -i 'gfortran'`" != "" ]; then
-    echo "WRFDA using gfortran needs realsize=8"
+  if [ "`grep '^SFC' configure.wrf | grep -i 'gfortran'`" != "" -o "`grep '^SFC' configure.wrf | grep -i 'frtpx'`" != "" ]; then
+    echo "WRFDA using gfortran/frtpx needs realsize=8"
     sed -e '/^PROMOTION.*=/s/#//' configure.wrf > configure.wrf.edit
     /bin/mv configure.wrf.edit configure.wrf
   fi
@@ -585,20 +767,23 @@ cat > ${foo}.f <<EOF
           end program test_exit
 EOF
 
-  # Detecting whether if mpi compiler wrapper supports -cc/-f90 options
-  if [ "`grep -i -E '^DMPARALLEL[ \t]*=.*#' configure.wrf`" = "" ]; then
-    mpicc -cc=$SCC -o ${foo} ${foo}.c > /dev/null 2>&1
-    if [ $? != 0 ]; then
-      sed 's/-cc=$(SCC)//' configure.wrf > configure.wrf.edit
-      mv configure.wrf.edit configure.wrf
+  # do not do this test for MIC, which cross compiles
+  if [ -z "`grep 'SCC.*mmic' configure.wrf`" ] ; then
+    # Detecting whether if mpi compiler wrapper supports -cc/-f90 options
+    if [ -z "`grep -i -E '^DMPARALLEL[ \t]*=.*#' configure.wrf`" ] ; then
+      mpicc -cc=$SCC -o ${foo} ${foo}.c > /dev/null 2>&1
+      if [ $? != 0 ]; then
+        sed 's/-cc=$(SCC)//' configure.wrf > configure.wrf.edit
+        mv configure.wrf.edit configure.wrf
+      fi
+      rm ${foo} ${foo}.o 2> /dev/null
+      mpif90 -f90=$SFC -o ${foo} ${foo}.f > /dev/null 2>&1
+      if [ $? != 0 ]; then
+        sed 's/-f90=$(SFC)//'  configure.wrf > configure.wrf.edit
+        mv configure.wrf.edit configure.wrf
+      fi
+      rm ${foo} ${foo}.o 2> /dev/null
     fi
-    rm ${foo} ${foo}.o 2> /dev/null
-    mpif90 -f90=$SFC -o ${foo} ${foo}.f > /dev/null 2>&1
-    if [ $? != 0 ]; then
-      sed 's/-f90=$(SFC)//'  configure.wrf > configure.wrf.edit
-      mv configure.wrf.edit configure.wrf
-    fi
-    rm ${foo} ${foo}.o 2> /dev/null
   fi
 
   if [ -e $NETCDF/lib/libnetcdf.a -a "$SFC" != "" -a "$SCC" != "" -a "$CCOMP" != "" ]; then
@@ -612,7 +797,7 @@ EOF
     echo Testing for NetCDF, C and Fortran compiler
     echo
 
-    ar p $NETCDF/lib/libnetcdf.a `ar t $NETCDF/lib/libnetcdf.a | grep -E '*\.o' | head -n 1 | sed 's/://'` > ${foo}.o
+    ar p $NETCDF/lib/libnetcdf.a `ar t $NETCDF/lib/libnetcdf.a | grep -E '\.o' | head -n 1 | sed 's/://'` > ${foo}.o
     netcdf_arch="`file ${foo}.o | grep -o -E '[0-9]{2}-bit|i386'`"
     rm ${foo}.o
 
@@ -682,7 +867,7 @@ EOF
 
       if [ $CROSS_COMPILING -eq 1 ] ; then
         echo NOTE:
-        echo This installation NetCDF is 32-bit
+        echo This installation of NetCDF is 32-bit
         if [ \( $SFC_MULTI_ABI -ne 1 -a "$SFC_arch" = "64-bit" \) \
              -o \( $SCC_MULTI_ABI -ne 1 -a "$SCC_arch" = "64-bit" \) \
              -o \( $CCOMP_MULTI_ABI -ne 1 -a "$CCOMP_arch" = "64-bit" \) ] ; then
@@ -736,7 +921,7 @@ EOF
 
       if [ $CROSS_COMPILING -eq 1 ] ; then
         echo NOTE:
-        echo This installation NetCDF is 64-bit
+        echo This installation of NetCDF is 64-bit
         if [ \( $SFC_MULTI_ABI -ne 1 -a "$SFC_arch" != "64-bit" \) \
             -o \( $SCC_MULTI_ABI -ne 1 -a "$SCC_arch" != "64-bit" \) \
             -o \( $CCOMP_MULTI_ABI -ne 1 -a "$CCOMP_arch" != "64-bit" \) ]; then
@@ -757,12 +942,127 @@ EOF
     fi
 
     if [ $CROSS_COMPILING -eq 0 ] ; then
-      echo This installation NetCDF is $netcdf_arch
-      echo C compiler is $SCC_arch
-      echo Fortran compiler is $SFC_arch
-      echo It will build in $netcdf_arch
+      echo "This installation of NetCDF is $netcdf_arch"
+      echo "                 C compiler is $SCC_arch"
+      echo "           Fortran compiler is $SFC_arch"
+      echo "              It will build in $netcdf_arch"
     fi
     echo
   fi
   rm -f ${foo} ${foo}.[cfo] 2> /dev/null
+fi
+
+# testing for Fortran 2003 IEEE signaling features
+make fortran_2003_ieee_test > tools/fortran_2003_ieee_test.log 2>&1
+rm -f tools/fortran_2003_ieee_test.log
+retval=-1
+if [ -f tools/fortran_2003_ieee_test.exe ] ; then
+  retval=0
+fi
+if [ $retval -ne 0 ] ; then
+  sed -e '/^ARCH_LOCAL/s/$/ -DNO_IEEE_MODULE/' configure.wrf > configure.wrf.edit
+  mv configure.wrf.edit configure.wrf
+  echo " "
+  echo " "
+  echo "************************** W A R N I N G ************************************"
+  echo " "
+  echo "There are some Fortran 2003 features in WRF that your compiler does not recognize"
+  echo "The IEEE signaling call has been removed.  That may not be enough."
+  echo " "
+  echo "*****************************************************************************"
+fi
+
+# testing for Fortran 2003 ISO_C features
+make fortran_2003_iso_c_test > tools/fortran_2003_iso_c_test.log 2>&1
+rm -f tools/fortran_2003_iso_c_test.log
+retval=-1
+if [ -f tools/fortran_2003_iso_c_test.exe ] ; then
+  retval=0
+fi
+if [ $retval -ne 0 ] ; then
+  sed -e '/^ARCH_LOCAL/s/$/ -DNO_ISO_C_SUPPORT/' configure.wrf > configure.wrf.edit
+  mv configure.wrf.edit configure.wrf
+  echo " "
+  echo " "
+  echo "************************** W A R N I N G ************************************"
+  echo " "
+  echo "There are some Fortran 2003 features in WRF that your compiler does not recognize"
+  echo "The routines that utilize ISO_C support have been stubbed out. "
+  echo "That may not be enough."
+  echo " "
+  echo "*****************************************************************************"
+fi
+
+# testing for Fortran 2003 FLUSH features
+make fortran_2003_flush_test > tools/fortran_2003_flush_test.log 2>&1
+rm -f tools/fortran_2003_flush_test.log
+retval=-1
+if [ -f tools/fortran_2003_flush_test.exe ] ; then
+  retval=0
+fi
+if [ $retval -ne 0 ] ; then
+  make fortran_2003_fflush_test > tools/fortran_2003_fflush_test.log 2>&1
+  rm -f tools/fortran_2003_fflush_test.log
+  retval=-1
+  if [ -f tools/fortran_2003_fflush_test.exe ] ; then
+    retval=0
+  fi
+  if [ $retval -eq 0 ] ; then
+    sed -e '/^ARCH_LOCAL/s/$/ -DUSE_FFLUSH/' configure.wrf > configure.wrf.edit
+    mv configure.wrf.edit configure.wrf
+    echo " "
+    echo " "
+    echo "************************** W A R N I N G ************************************"
+    echo " "
+    echo "There are some Fortran 2003 features in WRF that your compiler does not recognize"
+    echo "The standard FLUSH routine has been replaced by FFLUSH."
+    echo "That may not be enough."
+    echo " "
+    echo "*****************************************************************************"
+  fi
+  if [ $retval -ne 0 ] ; then
+    sed -e '/^ARCH_LOCAL/s/$/ -DNO_FLUSH_SUPPORT/' configure.wrf > configure.wrf.edit
+    mv configure.wrf.edit configure.wrf
+    echo " "
+    echo " "
+    echo "************************** W A R N I N G ************************************"
+    echo " "
+    echo "There are some Fortran 2003 features in WRF that your compiler does not recognize"
+    echo "The standard FLUSH routine has been stubbed out."
+    echo "That may not be enough."
+    echo " "
+    echo "*****************************************************************************"
+  fi
+fi
+
+# testing for netcdf4 IO features
+if [ -n "$NETCDF4" ] ; then
+  if [ $NETCDF4 -eq 1 ] ; then
+    make nc4_test > tools/nc4_test.log 2>&1
+    retval=-1
+    if  [ -f tools/nc4_test.exe ] ; then
+      retval=0
+      rm -f tools/nc4_test.log
+    fi
+    if [ $retval -ne 0  ] ; then
+      echo "************************** W A R N I N G ************************************"
+      echo "NETCDF4 IO features are enabled, but this installation of NetCDF             "
+      echo "  $NETCDF"
+      echo "sounds like DO NOT support these IO features.                                "
+      echo
+      echo "Please make sure NETCDF version is 4.1.3 or later and was built with         "
+      echo "--enable-netcdf4                                                             "
+      echo
+      echo "OR unset NETCDF4 variable                                                    "
+      echo "   bash/ksh : unset    NETCDF4                                               "
+      echo "        csh : unsetenv NETCDF4                                               " 
+      echo 
+      echo "Then re-run this configure script                                            "
+      echo
+      echo "!!! configure.wrf WAS REMOVED !!!"
+      echo
+      echo "*****************************************************************************"
+      rm -f configure.wrf
+    fi
+  fi
 fi
